baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = 'Hugo Theme - Midori'
# theme = 'midori'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[params]
    themeName = "Midori"
    version = "0.1.1"
  [params.author]
    name = 'KFACBT'
    email = 'gytxtx@outlook.com'

disableKinds = ["taxonomy", "term", "RSS"]

# ==========================================================
# Markdown 渲染设置
# ==========================================================
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # 设置为 true 以允许在 Markdown 文件中直接写 HTML 标签
      unsafe = true
